typography_spectrum: 0.45303041382858733
color:
  brandStrength: 0.39814548613374484
  lightness: 0.25448336133198574
  saturation: 0.13028901032430332
  rhythmicContrast: 0.051122037561997624
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
github: true
layout_spectrum: 0.2007845397213345
author:
  name: Dave Helmuth
  email: dave@adlibmusic.com
  url: 'https://adlibmusic.com'
name: Ad Lib Music
url: 'https://reconstructingchristmas.com'
navigation:
  - name: One
    id: 66771619-be19-4be4-9ee0-862bfdb988c3
    type: content
  - name: Two
    id: 84128d95-612e-41b6-a11b-6a30a24e5a8b
    type: content
  - name: Three
    id: 2b7593f9-420b-4c35-a9ed-b18c70808191
    type: content
  - name: Four
    id: 7f7e6aec-60a8-4c04-a337-77ee05f8e84a
    type: content
  - name: Five
    id: 04028ca0-1553-45e8-9972-050b25c83742
    type: content
title: Reconstructing Christmas
content: []
description: An honest journey back to the advent of Christmas
