typography_spectrum: 0.7763745134583868
color:
  brandStrength: 0.17700820946033197
  lightness: 0.11003444689030915
  saturation: 0.768342258894982
  rhythmicContrast: 0.568280389870766
  brandColors:
    - '#FFFFFF'
    - '#09080D'
    - '#755834'
    - '#DAD097'
    - '#958D5C'
github: true
layout_spectrum: 0.04506198255686403
author:
  name: Dave Helmuth
  email: dave@adlibmusic.com
  url: 'https://adlibmusic.com'
name: Ad Lib Music
url: 'https://reconstructingchristmas.com'
navigation:
  - name: One
    id: 66771619-be19-4be4-9ee0-862bfdb988c3
    type: content
  - name: Two
    id: 84128d95-612e-41b6-a11b-6a30a24e5a8b
    type: content
  - name: Three
    id: 2b7593f9-420b-4c35-a9ed-b18c70808191
    type: content
  - name: Four
    id: 7f7e6aec-60a8-4c04-a337-77ee05f8e84a
    type: content
  - name: Five
    id: 04028ca0-1553-45e8-9972-050b25c83742
    type: content
  - name: Six
    id: 92565be1-7f1e-4d18-be81-6728fb056c5a
    type: content
  - name: Seven
    id: 188e60d7-95f7-4039-8fb3-5d6a606fdc22
    type: content
title: Reconstructing Christmas
content: []
description: An honest journey back to the advent of Christmas
